name = "PICO_Fortran"
version = "0.1.0"
license = "Apache-2.0"
author = "dmr-dj"
maintainer = "didier.roche@lsce.ipsl.fr"
copyright = "Copyright 2022, dmr-dj"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
